alter table public.agency_experience_submissions
  add column if not exists resource_key text,
  add column if not exists public_rating text;

update public.agency_experience_submissions
set resource_key = 'v1:'
  || trim(both '-' from regexp_replace(lower(state), '[^a-z0-9]+', '-', 'g'))
  || ':'
  || trim(both '-' from regexp_replace(lower(agency_name), '[^a-z0-9]+', '-', 'g'))
where resource_key is null;

alter table public.agency_experience_submissions
  alter column resource_key set not null;

alter table public.agency_experience_submissions
  drop constraint if exists agency_experience_submissions_public_rating_check;

alter table public.agency_experience_submissions
  add constraint agency_experience_submissions_public_rating_check
  check (public_rating in ('trusted', 'not_helpful', 'possibly_dangerous'));

create index if not exists agency_experience_submissions_resource_rating_idx
  on public.agency_experience_submissions (state, resource_key, moderation_status, public_rating);

comment on column public.agency_experience_submissions.resource_key is
  'Deterministic v1 state-and-resource key generated by the application; no manual catalog IDs required.';

comment on column public.agency_experience_submissions.public_rating is
  'Community feedback category. Public APIs may expose aggregate counts only, never raw private submissions.';
